export PROJ_ROOT=$(shell pwd)
export D8_ROOT=${PROJ_ROOT}/web
export VENDOR=${PROJ_ROOT}/vendor
export CONTRIB=${D8_ROOT}/modules/contrib
export CUSTOM=${D8_ROOT}/modules/custom
export THEME=${D8_ROOT}/themes/custom
export D8_PATH=${D8_ROOT}/sites/default
export CONFIG=${PROJ_ROOT}/config
export ARCH=${PROJ_ROOT}/archive

export UUID=8fc6aae7-ae16-46a2-acb5-742c33c00387

export DATE=$(shell date '+%Y%m%d_%H%M%S')
export DBLINK=codex_drupal.sql
export DBFILE=codex_${DATE}.sql

export XTC=xtc xtcfile xtcguzzle xtcsearch yamlform dbmanager
export CDX=yamlform dbmanager wfk
export THEME=codex_theme
export OTHER=${PROJ_ROOT}
export INIT=xtcelastica xtcfile

include Makefile.git
